version: "3"
services:
  web:
    build: .
    image: my-django-app
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      DJANGO_SETTINGS_MODULE: backend.settings
    command:
      ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
    depends_on:
      - db
    
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

