# Generated by Django 4.2.4 on 2023-08-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grade5", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_title", models.CharField(max_length=255)),
                ("choice1", models.CharField(max_length=255)),
                ("choice2", models.CharField(max_length=255)),
                ("choice3", models.CharField(max_length=255)),
                ("choice4", models.CharField(max_length=255)),
                ("correct_choice", models.IntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="grade5.module",
                    ),
                ),
            ],
        ),
    ]
