# Generated by Django 4.2.4 on 2023-08-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade5", "0002_mcq"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="module",
            name="image1_is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="module",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="module",
            name="image2_is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="module",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="module",
            name="image3_is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="module",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="module",
            name="image4_is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="module",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="module",
            name="video_is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
