# Generated by Django 4.2.4 on 2023-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade5", "0003_alter_imagefield_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="mcq",
        ),
        migrations.AddField(
            model_name="content",
            name="mcqs",
            field=models.ManyToManyField(
                blank=True, related_name="contents", to="grade5.mcq"
            ),
        ),
    ]
