# Generated by Django 4.2.4 on 2023-08-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grade5", "0004_remove_content_mcq_content_mcqs"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCQSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="content",
            name="mcqs",
        ),
        migrations.RemoveField(
            model_name="mcq",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="content",
            name="mcq_set",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grade5.mcqset",
            ),
        ),
        migrations.AddField(
            model_name="mcq",
            name="mcq_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="grade5.mcqset",
            ),
        ),
    ]
